packages:
  - "apps/*"
  - "packages/*"

# These packages run install scripts to build native binaries or
# generate clients. They are required for the project to work.
allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  argon2: true
  esbuild: true
  prisma: true
  vue-demi: true
